### PR TITLE
Fix AMD worker language support imports

### PR DESCRIPTION
**Pull request by aangelisc**
This PR adds a fix for the paths used to import additional scripts using a web worker. When a web worker is used with the current relative paths the imports will fail due to CORS, making the library unusable. 

This change fixes the issue by allowing the base URL of the Monaco environment to be used (if defined) to provide a complete absolute path, allowing the scripts to be loaded from the same origin the worker is running from. This then allows the library to be served via CDN.

### CODE REVIEW

**Comment by sagivf** [comment]
@maxburs can we merge this?

**Comment by maxburs** [comment]
Hi @aangelisc, this seems like a great change.

Do you have any information (examples, docs, etc) about the Monaco environment getting passed to workers? I'd like to update our docs with more information about this.

**Comment by aangelisc** [comment]
Hi @maxburs, 

I have tested this within Grafana. As far as I can tell if the `MonacoEnvironment` property is defined on the `window` or globally then it will also be available in the workers global scope. I'm not sure if there is any concrete documentation on this..

**Comment by maxburs** [comment]
@aangelisc 

I attempted to read MonacoEnvironement in the worker without any luck:

image

Changes I made: https://github.com/Azure/monaco-kusto/compare/master...users/maburson/MonacoEnvironment

I tried to get something like this working previously, and concluded that the Monaco Editor isn't doing anything to copy MonacoEnvironment over to the workers.

I'd love to support this, but I also don't want to accept contributions if we don't have a way to test them. If you could give me any tips on getting this working, or update one of the examples, then I'd be happy to run with that and get this merged.

**Comment by aangelisc** [comment]
Hi @maxburs,

Sorry for the delay on this! I've found the relevant code [here](https://github.com/microsoft/vscode/blob/dbeea39df4ac933fe6d5395ad457dad4b494838b/src/vs/base/browser/defaultWorkerFactory.ts#L47). This is a part of the main VSCode code-base. It specifically pertains to handling the cross-origin case where the worker scripts are not being loaded from the location the application is running from.

If you setup an environment where the `monaco-kusto` package is not loaded from the same origin, but instead loaded from a CDN you will see this function be triggered and the `MonacoEnvironment` value will be set globally for the worker with the correct `baseUrl` value.

Let me know if this helps!

**Comment by aangelisc** [comment]
Hi @maxburs,

I've attached an example repo demonstrating the current behaviour and the behaviour of the fix. Let me know if you can reproduce now 😊 
[kusto-cdn-example.zip](https://github.com/Azure/monaco-kusto/files/11638036/kusto-cdn-example.zip)

**Comment by maxburs** [comment]
@aangelisc 

The link helped a lot. If we search for `MonacoEnvironment` we can even see them doing the same thing you do here in their worker entry point:

https://github.com/microsoft/vscode/blob/dbeea39df4ac933fe6d5395ad457dad4b494838b/src/vs/base/worker/workerMain.ts#L16

image

Relying on this makes a a little nervous? It's not clear to me that this is meant to be public api. I suppose if it ever breaks we can use the same trick they use by initializing the worker through a blob to pass state to it.

Could you add a few comments before we merge this? I don't think the code is self documenting, and I'd rather not start from scratch if it stops working.

Here's my take on what that might look like:
```ts
const AMD_WORKER_LANGUAGE_SERVER_IMPORT = `// If we're running in a web worker - which doesn't share global context with the main thread -
// we need to manually load dependencies that are not explicit- meaning our non-module dependencies
// generated by Bridge.Net
if (typeof document == 'undefined') {
    // Match how monaco defines the base url when inside a web worker: https://github.com/microsoft/vscode/blob/dbeea39df4ac933fe6d5395ad457dad4b494838b/src/vs/base/worker/workerMain.ts#L16
    //
    // MonacoEnvironment.baseUrl is conditional because monaco only sets it when the url is in a different origin.
    // Related monaco code: https://github.com/microsoft/vscode/blob/dbeea39df4ac933fe6d5395ad457dad4b494838b/src/vs/base/browser/defaultWorkerFactory.ts#L47
    //
    // It's not clear if this is meant to be a public api or not, so it may break
    const baseUrl = (MonacoEnvironment?.baseUrl || '../../../') + 'vs/language/kusto/';
    importScripts(
         baseUrl + 'bridge.min.js',
         baseUrl + 'kusto.javascript.client.min.js',
         baseUrl + 'newtonsoft.json.min.js',
         baseUrl + 'Kusto.Language.Bridge.min.js'
    );
}`;
```

@sagivf Do the comments I've written above make any sense? If this breaks in a year, would you have enough context?

**Comment by aangelisc** [comment]
Hi @maxburs,

I've updated the code with an improved comment (the one that you wrote above). I've also added a sample to demonstrate how this can be used.

Let me know if this is all sufficient!

**Comment by aangelisc** [comment]
@microsoft-github-policy-service agree

**Comment by maxburs** [comment]
Looks good! I hope I didn't imply that an example was necessary, but it's a welcome change.

I don't think it's going to pass ci because the lockfile is out of sync. Here's a PR to fix that, and clean a few other things up: https://github.com/aangelisc/monaco-kusto/pull/1

**Comment by aangelisc** [comment]
Thank you @maxburs! I've merged your changes so this should be good to go? If so how often do releases take place for this package?

No worries on adding the example, it took me some time to figure it out so I think this is a beneficial change for anyone looking to serve assets from a remote origin 😊

**Review by maxburs — APPROVED** [review]

**Comment by maxburs** [comment]
@aangelisc 7.4.0 is out and includes this change. We've got a pipeline that publishes new packages whenever we change the version.

I hope you don't mind that I pushed a commit to your branch that bumped the version and added back the babel config.

**Comment by aangelisc** [comment]
Thanks for all your help/work on this @maxburs 😊

**Pull request merged**
